// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxUpajNdR1ZqpRvzgBiVVMsUziRROD0o',
    appId: '1:377830803349:web:1c96dcffaf8aa23657d89c',
    messagingSenderId: '377830803349',
    projectId: 'fir-flutter-codelab-68c87',
    authDomain: 'fir-flutter-codelab-68c87.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-68c87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3d0HnmpisrcjTkYHS0tGNFxzrlgMjJP0',
    appId: '1:377830803349:android:2cd1997a1894a61d57d89c',
    messagingSenderId: '377830803349',
    projectId: 'fir-flutter-codelab-68c87',
    storageBucket: 'fir-flutter-codelab-68c87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv26ky8_dkDoBRKPxEBuqjBn96jUBnyVE',
    appId: '1:377830803349:ios:2e3af7438c90ee2957d89c',
    messagingSenderId: '377830803349',
    projectId: 'fir-flutter-codelab-68c87',
    storageBucket: 'fir-flutter-codelab-68c87.appspot.com',
    iosClientId: '377830803349-4i1c2o99fqqjql4gvdnegplvci2e32su.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv26ky8_dkDoBRKPxEBuqjBn96jUBnyVE',
    appId: '1:377830803349:ios:2e3af7438c90ee2957d89c',
    messagingSenderId: '377830803349',
    projectId: 'fir-flutter-codelab-68c87',
    storageBucket: 'fir-flutter-codelab-68c87.appspot.com',
    iosClientId: '377830803349-4i1c2o99fqqjql4gvdnegplvci2e32su.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
